name: Bug report
description: Create a report to help us improve
title: "[Version number] Issue subject goes here"
labels: Bug
assignees: []
body:
    - type: textarea
      attributes:
          label: Describe the Bug
          description: A clear and concise description of what the bug is
      validations:
          required: true
    - type: textarea
      attributes:
          label: Reproduction Steps
          description: Tell us about the steps to reproduce the bug
          value: |
              1.
              2.
              3.
              ...
      validations:
          required: true
