name: Questions & Other
description: The other options aren't what you're looking for? Create your own custom issue.
title: "Issue name"
labels: ["Question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!  

#        **Note:** Suggestion titles start with the square brackets that contain the **latest** full mod version.  
#        **Format:** [mod_loader]-[mod_version]+[minecraft_version]  
#        **Example: fabric-v1.0+1.19.2**
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is it you would like to ask?
      placeholder: Write the question here!
      value: "I would like to ask a question regarding..."
    validations:
      required: true
